[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
fs_permissions = [{ access = "read", path = "./src/AlienCodex/AlienCodex.json"}]

# See more config options https://github.com/gakonst/foundry/tree/master/config

ignored_error_codes = [2072, 2462, 2018]
